Module2 task1
htmlacademy-javascript/2343471-kekstagram-28 pull request #5
Opened 2023-03-08 20:51 UTC by rockNrol1

homework2

2023-03-17 08:39 UTC, yurylavrukhin commented on package.json
>      "lint": "eslint js/"
обязательно нужна запятая здесь, это же объект)

2023-03-17 08:40 UTC, yurylavrukhin requested changes
поправь запятую и проверки должны пройти)

2023-03-21 12:50 UTC, yurylavrukhin approved these changes
Фух, наконец-то мы это прошли :) Полетели вперёд!

2023-03-21 12:50 UTC, yurylavrukhin commented on js/function.js
> +myPadStart ('q', 4, 'we');
странно, что у нас есть пробелы перед круглыми скобками вызова функции, но ок, это код не ломает

попробуй запустить линтер с флагом --fix, он это сможет автоматически починить?

2023-03-21 12:50 UTC, yurylavrukhin commented on js/function.js
> +isStringLess ('проверяемая строка', 20);
Less не очень здесь подходит по смыслу, потому что это переводится как "меньше", название функции isStringShorterThan было бы получше

Поправлять это опционально :)

2023-03-21 12:50 UTC, merged

2023-03-22 04:22 UTC, rockNrol1 commented
Хорошо, спасибо, исправлю-запомню!--Отправлено из мобильной Яндекс Почты21.03.2023, 15:51, "Yury Lavrukhin" ***@***.***>:
@yurylavrukhin approved this pull request.

Фух, наконец-то мы это прошли :) Полетели вперёд!

In js/function.js:
> +//имяФункции('2023 год');            // 2023
+//имяФункции('ECMAScript 2022');     // 2022
+//имяФункции('1 кефир, 0.5 батона'); // 105
+//имяФункции('агент 007');           // 7
+//имяФункции('а я томат');           // NaN
+
+const myPadStart = (string, minLength, pad) => {
+  let result = string;
+  while (result.length < minLength) {
+    const newResultLength = result.length + pad.length;
+    const actualPad = newResultLength <= minLength ? pad : pad.slice (0, minLength - newResultLength);
+    result = actualPad + result;
+  }
+  return result;
+};
+myPadStart ('q', 4, 'we');

странно, что у нас есть пробелы перед круглыми скобками вызова функции, но ок, это код не ломает
попробуй запустить линтер с флагом --fix, он это сможет автоматически починить?



In js/function.js:
> +//имяФункции('проверяемая строка', 10); // false
+
+/*
+const isCheck =(string, length) => {
+return string.length <= length;
+}
+*/
+
+const isStringLess = (string, length) => {
+  if (string.length <= length) {
+    return true;
+  } else {
+    return false;
+  }
+};
+isStringLess ('проверяемая строка', 20);

Less не очень здесь подходит по смыслу, потому что это переводится как "меньше", название функции isStringShorterThan было бы получше
Поправлять это опционально :)

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>